# Generated by Django 3.2.2 on 2021-06-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
