# Generated by Django 3.2.2 on 2021-07-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_delete_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product',
            new_name='product_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(max_length=300),
        ),
    ]
