# Generated by Django 3.2.2 on 2021-07-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210707_1335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='title',
        ),
    ]
